### ISSUE TITLE
Fast mixnode launch with a pre-built ISO + VM software

### ISSUE THREAD

**Issue by mayurjobanputra** [nymtech/nym#1001]
I would love to be able to quickly spin up an instance of Nym using Oracle VM Virtualbox without having to worry about doing any configuration at all - or very minimal (eg: type in wallet address)

**Is your request a feature not related to an existing problem? A new feature.**
- Given I am new to Nym
- When I want to setup a Nym node
- Then I want to to set it up in less than 30 seconds

**Where does the feature fit in the Nym real estate?**
- User adoption

**What is this solving?**
Makes running a Nym node (and later validator) much easier

**Describe alternatives you've considered**
I'm seeing several blockchain projects with easy node launching. Strong has taken it a step further by doing all the infra in-house.

**Comment by tommyv1987** [comment]
Hi @mayurjobanputra 

Thank you for question / enhancement. It's on our agenda to do something more concrete in the near future, and another ticket has been raised. 

If you're looking for a quick set up in terms of installation, please refer to this script as provided by a nym user -  [script](https://github.com/gyrusdentatus/nym_autoinstall).

A few things will need to be changed in order to run the nodes due to the latest version upgrades. But this will be minimal.

Please keep an eye out in the near future for more ease of use deployments.

**Comment by mayurjobanputra** [comment]
OK great. Thanks @tommyv1987
