### ISSUE TITLE
Barf out all network-requester responses in native client as fast as they arrive

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#1495]
Check with Ania first to make sure this isn't crazy, but it would be a big perf optimization to do this.

**Comment by neacsu** [comment]
After checking with @aniampio, removing the Poisson distribution delays would have an impact not only on the network-requester (server) side, but it would also cause issues for the client side traffic analysis, possibly correlating client to server traffic.

In addition to that, after trying to disable the delays and also cover traffic for locally running client and server, using the mainnet mixnet, the improvements were marginal on traffic latency and throughput [1]. The main bottle-neck appears to be the mixing, as is to be expected.

The usability of the mixnet using socks5-type entry points depends heavily on the service application implementation. For example, when using big data transfers, keybase client <-> S3 transfers (for attachment upload & download) fail early due to timeouts, whereas `scp` transfers work more reliably by retrying every time to send chunks of data.

[1] For `scp` transfers, there was a 90 KB/s speed for a 20 MB file with the mixnet "as is", and a 120 KB/s speed for the same file, when removing the Poisson delays and the cover traffic.
