### ISSUE TITLE
[Feature Request] Auto Compound mode

### ISSUE THREAD

**Issue by MrGoldenpioche** [nymtech/nym#1608]
**Is your feature request related to a problem? Please describe.**
no

**Is your request a feature not related to an existing problem? A new feature.**
For example. 
- It could be great and useful if we can choose to enable or not an "auto compound mode".

**Where does the feature fit in the Nym real estate?**
- Application / UI -> Delegation -> Compound

**What is this solving?**
This new feature wil allow the user to reinject delegation NYM rewards automatically without the need to connect, check fee and reinject them. We can imagine to have an "Enabled / Disabled" switch to active this functionnality. The parameters are the following:
 - Rewards Threshold (NYM)
 - Fees limits (in percent of available NYM to compound)

While I don't know how fees are calculated, I don't know if we need to apply a "OR" or "AND" conditional logic between these two parameters. 

**Is this an update to packages or libraries?**
If so, please list them. If not, please ignore this section.

**Describe alternatives you've considered**
no alternative considered

**Additional context**

**Comment by tommyv1987** [comment]
hi @MrGoldenpioche 

Since our updated contract release, auto compounding is on by default.

For the time being we don't consider it to be an option now to have this feature flagged.

I will discuss this with the team, and will re-open the ticket if this becomes something we're looking to explore in the future.

Thank you for your detailed overview of the feature.
