### ISSUE TITLE
[Issue] User's desktop Telegram does not connect on chosen Socks5 proxy IP and port

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2175]
**Describe the issue**
User's desktop Telegram does not connect on chosen Socks5 proxy IP and port

**Expected behaviour**
Expected Telegram to connect 

**Steps to Reproduce**
launch NymConnect, choose Telegram, click Connect; open Telegram app, go to settings, advanced, connection types, use custom proxy and paste the IP and Port values given by NymConnect

**Screenshots**
https://prnt.sc/SkEeUuFj6Hi5

**Which area of Nym were you using?**
win 10, NymConnect, telegram desktop version 4.3.2 x64

**Comment by tommyv1987** [comment]
As mentioned in previous tickets, NC has made improvements on service provider selection, and new iterations have been deployed since. As for telegram, I can't validate their software as it may be a fault on their side. I've tried to reproduce the issue, but I've been unable to replicate it. Closing this ticket.
