### ISSUE TITLE
[Issue] After connecting Telegram to Nymconnect, Telegram is getting slower or stops working at all

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2180]
**Describe the issue**
After connecting Telegram to Nymconnect, Telegram is getting slower or stops working at all

**Expected behaviour**
 Telegram with Nymconnect will work normally, as usually

**Steps to Reproduce**
1. I open Nym Walllet
2. I open Nymconnect and connect wallet
3. Open telegram, fulfill all requirements and connect to Nymconnect
4. Sometimes it is work normally, but in most cases it is getting Telegram slower or stops working at all
5. Telegram shows that it try to connect, but Nymconnect shows that it is already connected 

*An example:*
- Given I was setting up a mix-node following the instructions in the docs
- And I successfully bonded my node via the the wallet
- When I went to start my mixnode
- Then I was presented with an error

**Screenshots**
(https://drive.google.com/drive/folders/1Sd9Azptd322_DK2sVWyvzeSpsI952Pjp)

**Which area of Nym were you using?**
Windows 10, Nyconnect, Nym Wallet 1.1.1

**Comment by tommyv1987** [comment]
Whilst nym-connect is an experimental piece of software, sometimes the latency on the network may be busier than usual. It can also depend on the performance of the service provider providing the connection to Telegram. We have since made changes to our service provider lists, who are grantees on our programs to provide core infrastructure when accessing the mixnet. The throughput should be better now, and we hope that the user isn't experiencing these issues. Closing the ticket as new iterations of NC have been released since this ticket. If the problem persists, please re-open the ticket
