### ISSUE TITLE
Wallet: optional gas and memo fields

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2222]
All transactions should have an advanced area where the user can specify the gas to use and/or to set a memo field

Comes from `HAL-06` of vesting contract audit.

The suggestion is to give the user can option of specifying the gas, so they can choose to provide a number to avoid overspend (we use 1.3x factor by default on the simulation to avoid failures).

The memo field is a nice feature to have.

---

**Let's check if we can do this only in Send**
Affects:

- send
- bond (liquid + locked)
- delegate (liquid + locked)
- undelegate (liquid + locked)
- withdraw vested tokens

![Image](https://user-images.githubusercontent.com/95295201/221607420-e1688a52-20ce-4dd0-aa56-59ba2818f12b.png)

- more options checkbox(same as advanced options in bonding flow)
- Description and two fields
- Gas field - whatever user put there will be displayed on next screen in summary - we are showing error if proposed fee is to low
- Memo optional field
- If user is using "Prefered Gas Fee" for this transaction we are displaying this in transaction summary
- If user typed something in memo input we are also showing this in summary(send details) screen

![Image](https://user-images.githubusercontent.com/95295201/221608628-a5e1eb7a-c2ac-433c-86f8-3d6524c6b770.png)

**Comment by jstuczyn** [comment]
I'd say we should have 3 modes of handling fees (like what cosmjs does), i.e.: pure simulation with 1.3x multiplier, simulation with custom multiplier and fully custom fee amount; do note however, that the last one could be a bit tricky because when specifying fees you need to provide any 2 pieces of information from the following: fee amount, gas limit and gas prices. The problem is that afaik there's no way to query validators for their current  gas prices and theoretically they could set them to whatever they want

**Comment by mmsinclair** [comment]
@doums the custom fee is entered in `NYM` and the Rust code will convert it to `crate::nyxd:Fee::manual` that takes a `cosmrs::tx::Fee` struct.

Use the default gas costs.

Show the user a reasonable error message if they specify too little gas - you can test it by supplying too little gas e.g. 1unym
