### ISSUE TITLE
[Issue]The password does not work and mnemonics contains an unknown word in Nym wallet

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2250]
**Describe the issue**
The user reinstalled the window and now He cannot enter the NYM wallet.
The password does not work
When entering mnemonics - mnemonics contains an unknown word (word 13)
Yesterday everything worked 

**Expected behaviour**
For a few more days your wallet worked, now it does not work, He did not change the password (

**Stack Traces**
If there are stack traces or logs, please provide them here...

**Steps to Reproduce**
He reinstalled Windows
Downloaded the NYM wallet from the official website
Installed a wallet
He enters the wallet by password - it does not enter
According to the Mnemonic phrase - writes an error

**Screenshots**
https://imgur.com/a/BxtYtl0

**Which area of Nym were you using?**
Windows 11
Intel - 4770k
RAM-32gb
SSD Samsung Evo 960

**Additional context**
User enters a mnemonic phrase from other wallets (Partisia wallet, Terra wallet) and it accepts the phrase and the wallet opens, but not his, completely different !

**Comment by rachyandco** [comment]
there could be a typo in the 13th word. user should check against this list https://www.blockplate.com/pages/bip-39-wordlist

**Comment by ZaratustraSlava** [comment]
Good afternoon. Thanks for the answer, I checked all the words and the error was in the 15th word (although the wallet shows that in the 13th word)
And I am also very interested. The bug that I found that you can enter the wallet by mnemonic phrase from wallets of other manufacturers - is this a big gap? 
And do you reward people like me - bug squasher ?

**Comment by rachyandco** [comment]
The fact that you can enter mnemonic generated in other wallet is by design. Most wallets, like Nym Wallet, follow Bitcoin BIP 39 specifications "Mnemonic code for generating deterministic keys" https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

Still it is not recommended for security reason to use the same mnemonic in different type of wallet, as one corrupted wallet could siphon funds from all wallets. We recommend generating 1 mnemonic code for each wallet you are using, and only entering them in an other wallet for recovery purposes.
