### ISSUE TITLE
[Issue]  Mixnode is mixing but user cant see his node in explorer

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2286]
**Describe the issue**
The problem is that. The user wanted to change his Bond amount, removed it, made unbond, re-entered the data of his node, double-checked everything correctly 300 times, pressed the bond, as a result, the packages in the terminal interferes. But there are no actions in the explorer, his knot has disappeared, it is not even inactive! It just doesn't exist, as if he doesnt have a node.

**Expected behaviour**
Ready after bond

**Steps to Reproduce**
1.unbond
2. Changed the value
3.Bond
**Screenshots**
no

**Which area of Nym were you using?**
macOS, Windows

**Comment by tommyv1987** [comment]
@merve64 apologies that this slipped through the net, can you confirm if this user is still experiencing problems. Since this ticket was raised, we've done a migration of contracts and multiple binary deployments. I'm going to close the ticket, but re-open it if you surface more information. Thank you
