### ISSUE TITLE
[Issue] Undelegate Keeps reporting errors

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2287]
**Describe the issue**
Undelegate Keeps reporting errors, see attachment

**Expected behaviour**
Normal Undelegate

**Steps to Reproduce**
Click Undelegate, click Confirm, then prompt for an error, wait an hour and still no Undelegate

**Screenshots**
https://imgur.com/XtgRAWJ
https://imgur.com/SMvEICW
https://imgur.com/09nzLlj

**Which area of Nym were you using?**
Windows 10 专业版 19044.1889
wallet Version 1.0.8

**Additional context**
If you need to provide additional information you can contact terrytu123@gmail.com

**Comment by sandglasstu** [comment]
Repeat display, merge to nymtech/nym#2283

**Comment by tommyv1987** [comment]
Apologies for responding to this much further down the line, than what it should've been. During our first iteration of our contract, we had some issues with transactions like this on the network. Since, we migrated to a new contract these issues, shouldn't persist no more. I'm going to close the issue, but please feel free to re-open if the issue persists and I can try to dig a bit deeper. Thank you.
