### ISSUE TITLE
Network explorer side bar behaviour

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2559]
Side bar open/close on both mobile and the desktop versions:

Unless the burger menu is selected, the side bar should automatically close once an item is selected. Currently it does not shrink back unless you click the < button.

On the Desktop, if possible, would be very useful if mouse over would automatically open the side bar! Just like the old explorer.

**Comment by tommyv1987** [comment]
Steps for testing:

Navigate to the feature branch `https://network-explorer-mobile-nav.ci.nymte.ch/nodemap`
Expand the menu and select the content items from inside the list.
Expected behaviour as mentioned in the requirements.

@Aid19801 — the behaviour to on `mouseEnter` on expand menu icon doesn't seem to be working, was this put into the branch too?

Devices tested: iphoneX
Browsers: Firefox, Brave
