### ISSUE TITLE
NC - add logs in the burger menu 🟢

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2683]
- [ ] 4 categories in the menu: Supported apps, Guide, Docs, Logs and version number at the bottom.
- [ ] When you click on Logs - a separate window with logs will appear over NC

**Comment by MarcinSN** [comment]
- [ ] Instead of help icon in top left corner we will have hamburger menu
- [ ] 3 categories in menu logs, guide and docs - in future we will have more
- [ ] When you click logs - separate window with logs will appear above wallet

![Image](https://user-images.githubusercontent.com/95295201/207828890-f36aaba3-53d3-4ce4-967e-f8e00b3f5098.png)
