### ISSUE TITLE
Fix dependabot Rust CI builds

### ISSUE THREAD

**Issue by octol** [nymtech/nym#2811]
As part of CI we run normal `clippy`, as well as a `clippy` step for generating github code view annotations. Possibly it's the latter of these that fail for dependabot PRs as it doesn't work for PRs raised from forked repos

Example: https://github.com/nymtech/nym/actions/runs/3873493152/jobs/6603572359

![image](https://user-images.githubusercontent.com/1894054/211568163-0ea36ee3-8d9b-4ade-b643-e6732ad385ca.png)

**Comment by farbanas** [comment]
Yep, the problem is `clippy-check` GH action. Due to some changes in GH actions `clippy-check` doesn't have enough permissions to actually annotate the PR. Adding the permissions to the workflow solves the problem but it's not recommended by Github and is considered a security risk.

Github added a new feature called pattern matchers which should be used for this problem, but that should most likely be implemented on the `clippy-check` side of things.

I'll test out a few options to see what's best to make this not failing at least.

**Comment by farbanas** [comment]
~~Ok, seems that just adding a `name` parameter to the `clippy-check` GH action solves the problem. Will create a PR with that.~~

Update: This was a wrong assumption, permissions persisted through builds so that build had write permissions. The correct solution is to continue on error since that clippy check never fails if it finds some errors/warning so it will only fail on permission errors (and then we want to continue and not fail).
