### ISSUE TITLE
Wallet - change the Bonding flow to include an additional step for the user to provide a unique signature when they bond their node

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#3109]
Bonding flow update

- 3 steps instead of 2

1 step
we are deleting signature field from form

![Image](https://user-images.githubusercontent.com/95295201/221609265-abe86b0d-758f-416f-898f-2007509fa33a.png)

2 step - new one

we are providing message - user is signing in this message outside the wallet and after that pasting signature in input

![image](https://user-images.githubusercontent.com/95295201/221860403-dc9570db-cd55-4515-8202-39cdffc393e5.png)

3 step same as it was(previously second step)

**Comment by jstuczyn** [comment]
The requires rust-side is done here: https://github.com/nymtech/nym/pull/3126. However, as I noted on matrix, I do expect this branch to undergo few more rebases since it relies on `audit-fixes` branch that's not merged yet.

The relevant tauri commands to generate the payloads are:
- `generate_mixnode_bonding_msg_payload`,
- `vesting_generate_mixnode_bonding_msg_payload`
- `generate_gateway_bonding_msg_payload`
- `vesting_generate_gateway_bonding_msg_payload`

The mixnode/gateway command you need to generate the signature is 
`nym-mixnode sign --id <your-node-id> --contract-msg <payload-generated-by-the-wallet>`
`nym-gateway sign --id <your-node-id> --contract-msg <payload-generated-by-the-wallet>`

**Comment by doums** [comment]
UI part https://github.com/nymtech/nym/pull/3157 WIP
