### ISSUE TITLE
Native client API: fragmentation and SURBs

### ISSUE THREAD

**Issue by sgeisler** [nymtech/nym#340]
I'm currently thinking about how I can fix my [Nym hidden service provider](https://github.com/sgeisler/nym_hs) using SURBs. Doing that I came up with some questions/remarks:

1. What's the maximum message size that will not result in fragmentation? Or is fragmentation even done by default? I'd really like a API with a defined "MTU" that guarantees no fragmentation will happen (possibly related to #294).
2. Said API should only do unreliable sends, so no SURB ACKs and resending. I know you wanted to make the message sending reliable, but haven't found if you already did it yet. Anyway, for some protocols more control is nice to avoid unnecessary latency.
3. SURBs shouldn't be part of this low level protocol. I'd rather have a function to request SURBs from my node to include them in my protocol as required. That way a bidirectional protocol could indicate the buffer size for each direction and either allocate more space to SURBs or stream data depending on which direction under heavier load.

I hope these points make sense to you. It feels like the fancy reliable and fragmenting version of the protocol mentioned in #294 could be built on top of this simpler version. I'm not sure how well using them alongside each other would work, so maybe one would need to decide on startup? Or should I just build a completely separate client at that point? I'd really like to avoid that to not fuck up something important like cover traffic that I don't fully understand and would be just copying.

**Comment by jstuczyn** [comment]
Ah! Sorry for such a late reply - I have not noticed your issue here until now! Let me try to answer your questions.

>1. What's the maximum message size that will not result in fragmentation.

Right now that's 2kB as defined in `https://github.com/nymtech/nym/blob/develop/common/nymsphinx/params/src/packet_sizes.rs#L21`, but this might change down the line. However, client itself is totally oblivious to all fragmentation happening - it can send and receive messages of arbitrary sizes. The fragmentation (and reconstruction) would happen behind the scenes.

> 2. Said API should only do unreliable sends, so no SURB ACKs and resending.

That's an interesting idea, but right now the SURB ACK reliability is rather deep embedded into the system - the receiving gateway expects a SURB-ACK in the packet to send it back into the network. I'm not sure if that was changed whether your packets might not become distinguishable from other packets on the network simply because they would not contain that SURB-ACK @futurechimp @aniampio any ideas here?

> 3. SURBs shouldn't be part of this low level protocol.

We're currently thinking about how to redesign SURBs to make it all slightly more flexible and requesting SURBs based on usage. Any suggestions are welcome :) 

And as for the "fancy" fragmentation mentioned in #294 it's mostly to simplify the current method that in hindsight is waaay over engineered : ) And maybe hopefully introduce some additional features.
