### ISSUE TITLE
[FEATURE REQUEST] add option to can bind nym-socks5-client to 0.0.0.0 instead of 127.0.0.1 with a "--host" flag

### ISSUE THREAD

**Issue by twofaktor** [nymtech/nym#3477]
**Where does the feature fit in the Nym real estate?**
nym-socks5-client / Nym Connect 

**What is this solving?**
Add option to can bind nym-socks5-client to 0.0.0.0 instead of 127.0.0.1 with a "--host" flag without using docker
This could be useful to use socks5 client from other different machines in the same local network

**Is this an update to packages or libraries?**
I don't know

**Additional context**
There is a method to get this, but only using docker: https://nymtech.net/docs/clients/socks5-client.html#configuring-your-client-for-docker
I'm not using docker

When I try to use the flag in command: `./nym-socks5-client init --id docs-example --host 0.0.0.0`
output:
`error: unexpected argument '--host' found`

**Comment by serinko** [comment]
When you run `./nym-socks5-client init --id docs-example --host 0.0.0.0` you get that error because the `init` command does not have that option. See:
`./nym-socks5-client init --help`

The rest of the feature request is sound, I will make sure to bring it up to the team next week and see where we can get.
