### ISSUE TITLE
[Issue] Links not opening in browser from Wallet

### ISSUE THREAD

**Issue by snek** [nymtech/nym#3550]
**Describe the issue**
When using the Nym Wallet under Ubuntu Linux most of the links in the wallet do not actually open up a browser window. Under `Delegation` the link `Network Explorer` does nothing for example. Under `Buy` the button `Buy NYM` does nothing. Under `Balance` the `Last Transactions` link does nothing.

**Expected behaviour**
I expect a browser window to be opened or maybe a popup as seen in Google Sheets where one can follow the link or copy/paste it from a text input.

**Steps to Reproduce Last Transactions Bug**
- Given I am running Ubuntu Linux 22.04
- When I open the nym-wallet_1.2.3_amd64.AppImage
- And I click on `Last Transactions` under `Balance`
- Then I expect to have a browser opened to the appropriate page

**Steps to Reproduce Network Explorer Bug**
- Given I am running Ubuntu Linux 22.04
- When I open the nym-wallet_1.2.3_amd64.AppImage
- And I click on `Network Explorer` under `Delegation`
- Then I expect to have a browser opened to the appropriate page

**Steps to Reproduce Buy NYM Bug**
- Given I am running Ubuntu Linux 22.04
- When I open the nym-wallet_1.2.3_amd64.AppImage
- And I click on `Buy NYM` under `Buy`
- Then I expect to have a browser opened to the appropriate page

**Which area of Nym were you using?**
- nym-wallet_1.2.3_amd64.AppImage
- Ubuntu 22.04.2 LTS
- Default browser: Chromium

**Additional context**
I've been having this issue for ages

**Comment by mmsinclair** [comment]
@tommyv1987 @serinko would you mind seeing if this still fails in the latest wallet?

**Comment by serinko** [comment]
Sure thing. Reproducing: Running [nym-wallet-v1.2.10](https://github.com/nymtech/nym/releases/tag/nym-wallet-v1.2.10) on Debian.

- [x] Last transaction under Balance ✅
- [x]  Buy Nym ✅
- [x] Network Explorer under Delegation ✅

Thank you for the issue @snek , I believe that all of those were addressed since the time you tried it. If you still have the same problem, I would look into your browser setting how it handles opening new links. 
You can check the wallet functionality by right click on each of the links, copy link and paste to your browser.
