### ISSUE TITLE
create operator-specific documentation mdbook project

### ISSUE THREAD

**Issue by mfahampshire** [nymtech/nym#3577]
* [x] Create something like `nymtech.net/operators` mdbook project

**Comment by serinko** [comment]
* [x] pull setup guides and node operator troubleshooting into there from docs
  - Under construction here: https://github.com/nymtech/nym/tree/feature/operators-guide/documentation/operators
* Create pages for:
    - [x] [preliminary steps](https://github.com/nymtech/nym/blob/feature/operators-guide/documentation/operators/src/preliminary-steps.md) - generic for all nodes
    - [x] [mixnode page](https://github.com/nymtech/nym/blob/feature/operators-guide/documentation/operators/src/nodes/mix-node-setup.md)
    - [x] [gateway page](https://github.com/nymtech/nym/blob/feature/operators-guide/documentation/operators/src/nodes/gateway-setup.md) 
    - [x] [NR page](https://github.com/nymtech/nym/blob/feature/operators-guide/documentation/operators/src/nodes/network-requester-setup.md)
    - [x] [validator page](https://github.com/nymtech/nym/blob/feature/operators-guide/documentation/operators/src/nodes/validator-setup.md)
    - [x] [maintenance page](https://github.com/nymtech/nym/blob/feature/operators-guide/documentation/operators/src/nodes/maintenance.md) - merge all nodes upgrades, firewall, automation, ports, etc..
    - [x] [troubleshooting](https://github.com/nymtech/nym/blob/feature/operators-guide/documentation/operators/src/nodes/troubleshooting.md)
    - [x] [FAQ](https://github.com/nymtech/nym/blob/feature/operators-guide/documentation/operators/src/faq.md) - Propose to leave this one commented and fill it after the book release as this page is of a dynamic nature, not like others. 
* [x] Incorporate [#3699](https://github.com/nymtech/nym/pull/3699) across the docs
* [x] Build the book
* [x] Go through all the TODO details (on top of every doc)
* [x] GET NEW THEME FOR ALL THE MDBOOKS
* [ ] Get a new webpage - in construction
* [x] setup a bot channel in matrix - in construction 
* [x] Go through every single hyper-link again to make sure they work correctly (especially the ones linking back to thew docs due to formating when `build`)
* [x] - final bits of changed content for the nodes in `docs`
* [x] - checking links etc (partially automated but we need to make sure we don't have hardcoded version links in any github links - links can use the version variable)
* [x] checking that all review comments are resolved
* [x] - getting links in start pages of developers and docs to explain + point to operators
    * [x] - `doc`
    * [x] - `dev-portal`
* [ ] - get raphael to sort out the dns
* [ ] - get a final version in a staging server and do final check through
