### ISSUE TITLE
nym-socks5-client high CPU usage on idle

### ISSUE THREAD

**Issue by rex4539** [nymtech/nym#491]
Steps:
Start the client and be idle. No proxy connections active.

What happened:
CPU usage is constantly at around 140%, even if you wait for 30mins.

<img width="1184" alt="Screen Shot 2020-12-28 at 11 24 24" src="https://user-images.githubusercontent.com/227442/103204430-06edaf80-4900-11eb-8965-8b768614ccd9.png">

[Sample of nym-socks5-client.txt](https://github.com/nymtech/nym/files/5746606/Sample.of.nym-socks5-client.txt)

Expected result:
Low CPU usage on idle.

**Comment by jstuczyn** [comment]
Well, this is not really a bug. It doesn't matter if your client has any proxy connections established, it is always sending to the mix network with the same Poisson rate. If it does not have a 'real' message on hand, it will instead send a cover message. And so the CPU usage will remain mostly constant as the most computationally intensive part is creation of Sphinx packets and their number, on average per unit of time, does not change.

**Comment by rex4539** [comment]
If it's by design that the client uses 140% CPU constantly, then there is obviously a design flaw.

Who will ever use a client that uses that many resources? The maximum acceptable constant CPU usage is something around 1% CPU.

**Comment by futurechimp** [comment]
Hi @rex4539!

At the moment we're concentrating on building a system that implements the full mixnet guarantees, in the purest form (highest security) we can. It is not an easy thing to build a network privacy system that can withstand very strong and well-resourced adversaries, but we think we have succeeded in that (caveat: we still need to do security audits, subject it to sophisticated attacks, etc).

As far as I'm aware, there is no other system on the planet that can defeat end-to-end correlation attacks by adversaries who are able to record the entirety of internet traffic. In that sense, the system is basically the network security equivalent of a tank, which of course takes more resources to run than a car or a motorcycle. If you want to be able to win against extremely powerful attackers, usually you need to spend more in terms of resources. I have not seen any more efficient system proposed in the past 20 years or so that will do this job. People are working on it, but currently this is the state of the art. 

As to the practicality part, you're right -  I agree, CPU usage is too high right now. But it's worth saying - we have not been working to optimize performance yet. 

Now that we have built the high-strength low-performance system, the fun can begin. Nobody has ever deployed a 1500-node general-purpose mixnet before, so we are in completely uncharted territory. But we are starting to research privacy vs performance sweet spots for different users and uses.

At the moment, we have the "privacy vs performance" dial turned all the way over to point only at "privacy". Are there ways that we can do less key derivation, which is what's currently cranking the CPU? We know the answer here is yes, we can do this in several different ways. But what are the impacts on e.g. latency, throughput, entropy levels, etc? The universe never gives us anything for free, so there are going to be trade-offs. 

Having said all that, I'm pretty confident that there will be a sweet spot which balances resource usage, latency, throughput, and privacy levels. We just need to find out what the optimum is (the optimum may differ for different types of user as well, so we will likely make this stuff configurable). That's our task for 2021 when it comes to the mixnet.
