### ISSUE TITLE
nym-socks5-client is painfully slow

### ISSUE THREAD

**Issue by rex4539** [nymtech/nym#495]
Reproducibility: always

Steps:
On Keybase, click on "People" tab.

What happened:
<img width="1291" alt="Screen Shot 2021-01-09 at 16 57 54" src="https://user-images.githubusercontent.com/227442/104094804-d7458c80-529b-11eb-9e6a-09905a7bf7ce.png">

Expected result:
nym-socks5-client is not slow.

**Comment by tommyv1987** [comment]
Hi @rex4539,

Thank you for raising this issue, and sorry it's taken some time to get in touch with you.

We acknowledged that client may not be as performant as it should, but we've been improving the network since you've raised this issue. We are continuing to work on it, and it has been factored in elsewhere. 

Going to close this issue.
