### ISSUE TITLE
Cannot assign requested address

### ISSUE THREAD

**Issue by qhm1227** [nymtech/nym#584]
thread 'tokio-runtime-worker' panicked at 'Failed to create TCP listener: Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }', mixnode/src/node/listener/mod.rs:24:14

How to fix this?

**Comment by jstuczyn** [comment]
You need to make sure that no other process is already running on your target port (most likely `1789`) and that you didn't accidentally mistype the address you wanted to bind to. Furthermore, if your machine has a different internal and external address, you might be unable to directly bind to the external one (that's why `--announce-address` flag exists. Refer to our docs for more information: https://nymtech.net/docs/run-nym-nodes/mixnodes/#virtual-ips-google-aws-and-all-that ). For any further questions, please send them on either keybase (preferable) or telegram as this is not a software issue
