### ISSUE TITLE
Replace args with proper config files

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#69]
At the moment, mixnode keys change on every node restart. This is going to cause friction for clients (especially if they don't refresh periodically) because a restarted node will change its key, causing MacIntegrity errors as clients send un-decryptable packets. Ultimately this breaks the path, a big no-no.

So we might as well store some persistent information on disk.

* make an `init` command for mixnodes and providers
* create persistent mixnode keys that survive across restarts
* we need to consider whether we need node human names for this

**Comment by jstuczyn** [comment]
Having config file will also allow us more fine grained control over the application. It might be for example useful to set maximum number of threads you want to be using so that mixnode (or client or whatever) wouldnt use too much resources. This particular example can be set with https://docs.rs/tokio/0.2.9/tokio/runtime/struct.Builder.html#method.core_threads
