### ISSUE TITLE
[Issue] React Example doesn't compile with wasm package local build

### ISSUE THREAD

**Issue by ghost** [nymtech/nym#877]
**Describe the issue**
When I try to start the react-example project to test the webassembly client with the wasm package locally built, I get an error when compiling the react-dev-server

**Expected behaviour**
The project should properly compile and start when using the wasm package locally built

**Steps to Reproduce**
- Given I was trying the webassembly client with the react-example project
- And I compiled succesfully the webassembly rust client locally
- When I started the dev-server
- Then I got a compiling error

**Screenshots**
<img width="882" alt="Screenshot 2021-11-04 at 13 56 21" src="https://user-images.githubusercontent.com/47139070/140317339-c52620f4-8d96-48ea-b9a8-218cc97ea930.png">

**Which area of Nym were you using?**
 - Application:  WebAssembly client
 - OS: MacOs BigSur
 - Browser: Brave, Firefox
 - Version: nym binary(0.11.0)

**Comment by shark-o** [comment]
Using [fluvio-wasm-timer](https://docs.rs/fluvio-wasm-timer/latest/fluvio_wasm_timer/) in `common/client-libs/gateway-client` seems to fix it.

After that Im getting error:
```
nym_client_wasm_bg.js:179 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at passStringToWasm0 (nym_client_wasm_bg.js:179)
    at new NymClient (nym_client_wasm_bg.js:378)
    at main (index.js:29)
    at eval (index.js:113)
    at Module../index.js (0.bootstrap.js:57)
    at __webpack_require__ (bootstrap.js:366)
passStringToWasm0 @ nym_client_wasm_bg.js:179
NymClient @ nym_client_wasm_bg.js:378
main @ index.js:29
eval @ index.js:113
./index.js @ 0.bootstrap.js:57
__webpack_require__ @ bootstrap.js:366
Promise.then (async)
eval @ bootstrap.js:4
./bootstrap.js @ bootstrap.js:548
__webpack_require__ @ bootstrap.js:366
eval @ client:2
0 @ bootstrap.js:935
__webpack_require__ @ bootstrap.js:366
(anonymous) @ bootstrap.js:536
(anonymous) @ bootstrap.js:539
```

That seems to be thrown because `mixnet_contract_address` is not provided.

To fix it I used `native-client` and `validator_rest_urls[0]` and `mixnet_contract_address` from `$HOME/.nym/clients/<client-id>/config/config.toml` when creating NymClient in `clients/webassembly/js-example/index.js`.

It also seems that as long as `validator_rest_url` is valid you can just assign empty string for `mixnet_contract_address`.

```
client = new NymClient(validator, "");
```

BTW This was done on tag `v0.11.0` because `development` head is broken.

**Comment by tommyv1987** [comment]
A lot of work has been done recently to align the wasm client to be functional with the latest mixnet. Therefore closing this ticket.
